kind: Deployment
apiVersion: apps/V1
metadata:
  name: microservice3-deployment
  namespace: surya-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: surya
  template:
    metadata:
      labels:
        app: surya
    spec:
      containers:
        - name: microservices-deployment
          image: us-central1-docker.pkg.dev/prefab-icon-441814-j7/surya-artifact/microservice3:latest
          ports:
            - containerPort: 8080
              protocol: TCP

---
kind: Service
apiVersion: v1
metadata:
  name: microservice-3
spec:
  selector:
    labels:
      app: surya
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP




