name: microservices-kubernetes

on:
  push:
    branches:
      - teja

jobs:
  deploy-microservices:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout to Branch"
        uses: actions/checkout@v4

      - name: "Install Java"
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: "Install Maven"
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

#      - name: "Clean target "
#        run: |
#          #!/bin/bash
#          mvn clean package
#        shell: bash

      - name: 'Setup GCP SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Authenticate SA'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SA }}

      - name: "Build JAR for Microservice 1"
        run: |
          #!/bin/bash
          mvn clean package
          mvn package --file microservice-kubernetes-demo-catalog/pom.xml

      - name: "Build Docker Image for Microservice-1"
        run: |
          #!/bin/bash
          docker build -t microservice1 ./microservice-kubernetes-demo-catalog
        shell: bash

      - name: "Tag and push Microservice-1 images to GAR"
        run: |
          #!/bin/bash
          docker tag microservice1 us-central1-docker.pkg.dev/prefab-icon-441814-j7/surya-artifact/microservice1:latest
          docker push us-central1-docker.pkg.dev/prefab-icon-441814-j7/surya-artifact/microservice1:latest

      - name: "Build JAR for Microservice-2"
        run: |
          #!/bin/bash
          mvn clean package
          mvn package --file microservice-kubernetes-demo-customer/pom.xml

      - name: " Build Image for Microservice-2"
        run: |
          #!/bin/bash
          docker build -t microservice2 ./microservice-kubernetes-demo-customer

      - name: "Tag and push images to GAR"
        run: |
          #!/bin/bash
          docker tag microservice2 us-central1-docker.pkg.dev/prefab-icon-441814-j7/surya-artifact/microservice2:latest
          docker push us-central1-docker.pkg.dev/prefab-icon-441814-j7/surya-artifact/microservice2:latest

      - name: "Build JAR files for Microservice-3"
        run: |
          #!/bin/bash
          mvn clean package
          mvn package --file microservice-kubernetes-demo-order/pom.xml
        shell: bash

      - name: "Build Image for Microservice-3"
        run: |
          #!/bin/bash
          docker build -t microservice3 ./microservice-kubernetes-demo-order
        shell: bash

      - name: "Tag and push images to GAR"
        run: |
          #!/bin/bash
          docker tag microservice3 us-central1-docker.pkg.dev/prefab-icon-441814-j7/surya-artifact/microservice3:latest
          docker push us-central1-docker.pkg.dev/prefab-icon-441814-j7/surya-artifact/microservice3:latest

      - name: "Install Kubernetes"
        run: |
          #!/bin/bash
          gcloud components install kubectl gke-gcloud-auth-plugin
          gcloud config set project prefab-icon-441814-j7
          gcloud config set compute/region us-central1
          gcloud container clusters get-credentials surya-gke-cluster -- region=us-central1
          
          kubectl version --client
        shell: bash

      - name: "Create Deployment"
        run: |
          #!/bin/bash
          kubectl apply -f deployment-k8/microservice1-deployment.yaml
          kubectl apply -f deployment-k8/microservice2-deployment.yaml
          kubectl apply -f deployment-k8/microservice3-deployment.yaml
        shell: bash

        working-directory: k8